CREATE FUNCTION hello (s VARCHAR(300))
RETURNS VARCHAR(300) DETERMINISTIC
RETURN REPLACE('јбаза','а','i'); 

CREATE FUNCTION test_func()
RETURNS INT
BEGIN
	SELECT 'Hello World';
RETURN 1;
END;$$

DROP FUNCTION IF EXISTS hello;

DELIMITER $$
REATE FUNCTION hello (s VARCHAR(300))
RETURNS VARCHAR(300) DETERMINISTIC
RETURN REPLACE('јбаза','а','i');$$
DELIMITER;