INSERT INTO region (abbr, region_name,region_name_latin) values
("AL","Alabama","Alabama"),
("AK","Alaska","Alaska"),
("AZ","Arizona","Arizona"),
("AR","Arkansas","Arkansas"),
("CA","California","California"),
("CO","Colorado","Colorado"),
("CT","Connecticut","Connecticut"),
("DE","Delaware","Delaware"),
("FL","Florida","Florida"),
("GA","Georgia","Georgia"),
("HI","Hawaii","Hawaii"),
("ID","Idaho","Idaho"),
("IL","Illinois","Illinois"),
("IN","Indiana","Indiana"),
("IA","Iowa","Iowa"),
("KS","Kansas","Kansas"),
("KY","Kentucky","Kentucky"),
("LA","Louisiana","Louisiana"),
("ME","Maine","Maine"),
("MD","Maryland","Maryland"),
("MA","Massachusetts","Massachusetts"),
("MI","Michigan","Michigan"),
("MN","Minnesota","Minnesota"),
("MS","Mississippi","Mississippi"),
("MO","Missouri","Missouri"),
("MT","Montana","Montana"),
("NE","Nebraska","Nebraska"),
("NV","Nevada","Nevada"),
("NH","New Hampshire","New-Hampshire"),
("NJ","New Jersey","New-Jersey"),
("NM","New Mexico","New-Mexico"),
("NY","New York","New-York"),
("NC","North Carolina","North-Carolina"),
("ND","North Dakota","North-Dakota"),
("OH","Ohio","Ohio"),
("OK","Oklahoma","Oklahoma"),
("OR","Oregon","Oregon"),
("PA","Pennsylvania","Pennsylvania"),
("PR","Puerto Rico","Puerto-Rico"),
("RI","Rhode Island","Rhode-Island"),
("SC","South Carolina","South-Carolina"),
("SD","South Dakota","South-Dakota"),
("TN","Tennessee","Tennessee"),
("TX","Texas","Texas"),
("UT","Utah","Utah"),
("VT","Vermont","Vermont"),
("VA","Virginia","Virginia"),
("WA","Washington","Washington"),
("WV","West Virginia","West-Virginia"),
("WI","Wisconsin","Wisconsin"),
("WY","Wyoming","Wyoming");