INSERT INTO extra_key (key_value,key_value_latin) select 'банк тинкофф',encodestring('банк тинкофф');
INSERT INTO extra_key (key_value,key_value_latin) select 'частный кредит',encodestring('частный кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'кредит на автомобиль',encodestring('кредит на автомобиль');
INSERT INTO extra_key (key_value,key_value_latin) select 'кредит под недвижимость',encodestring('кредит под недвижимость');
INSERT INTO extra_key (key_value,key_value_latin) select 'оформить кредит',encodestring('оформить кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'кредит в банке',encodestring('кредит в банке');
INSERT INTO extra_key (key_value,key_value_latin) select 'ренессанс кредит',encodestring('ренессанс кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'банк русский стандарт',encodestring('банк русский стандарт');
INSERT INTO extra_key (key_value,key_value_latin) select 'сайт кредитов',encodestring('сайт кредитов');
INSERT INTO extra_key (key_value,key_value_latin) select 'кредит без справок',encodestring('кредит без справок');
INSERT INTO extra_key (key_value,key_value_latin) select 'коммерческий кредит',encodestring('коммерческий кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'кредит',encodestring('кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'кредит без взноса',encodestring('кредит без взноса');
INSERT INTO extra_key (key_value,key_value_latin) select 'автокредит',encodestring('автокредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'выгодный кредит',encodestring('выгодный кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'кредит физическим лицам',encodestring('кредит физическим лицам');
INSERT INTO extra_key (key_value,key_value_latin) select 'кредит онлайн',encodestring('кредит онлайн');
INSERT INTO extra_key (key_value,key_value_latin) select 'машина в кредит',encodestring('машина в кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'банк хоум кредит',encodestring('банк хоум кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'кредит на жилье',encodestring('кредит на жилье');
INSERT INTO extra_key (key_value,key_value_latin) select 'банковский кредит',encodestring('банковский кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'кредит без дохода',encodestring('кредит без дохода');
INSERT INTO extra_key (key_value,key_value_latin) select 'лучшие кредиты',encodestring('лучшие кредиты');
INSERT INTO extra_key (key_value,key_value_latin) select 'кредит наличными',encodestring('кредит наличными');
INSERT INTO extra_key (key_value,key_value_latin) select 'кредит без поручителей',encodestring('кредит без поручителей');
INSERT INTO extra_key (key_value,key_value_latin) select 'кредит для бизнеса',encodestring('кредит для бизнеса');
INSERT INTO extra_key (key_value,key_value_latin) select 'дебет кредит',encodestring('дебет кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'где взять кредит',encodestring('где взять кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'быстрый кредит',encodestring('быстрый кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'получение кредита',encodestring('получение кредита');
INSERT INTO extra_key (key_value,key_value_latin) select 'кредит под залог',encodestring('кредит под залог');
INSERT INTO extra_key (key_value,key_value_latin) select 'кредит на жильё',encodestring('кредит на жильё');
INSERT INTO extra_key (key_value,key_value_latin) select 'краткосрочный кредит',encodestring('краткосрочный кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'кредит малому бизнесу',encodestring('кредит малому бизнесу');
INSERT INTO extra_key (key_value,key_value_latin) select 'беспроцентный кредит',encodestring('беспроцентный кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'хоум кредит',encodestring('хоум кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'экспресс кредит',encodestring('экспресс кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'кредит пенсионерам',encodestring('кредит пенсионерам');
INSERT INTO extra_key (key_value,key_value_latin) select 'кредитные карты',encodestring('кредитные карты');
INSERT INTO extra_key (key_value,key_value_latin) select 'взять кредит',encodestring('взять кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'международный кредит',encodestring('международный кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'ипотечный кредит',encodestring('ипотечный кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'потребительский кредит',encodestring('потребительский кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'материнский кредит',encodestring('материнский кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'банк ренессанс',encodestring('банк ренессанс');
INSERT INTO extra_key (key_value,key_value_latin) select 'кредит без первоначального взноса',encodestring('кредит без первоначального взноса');
INSERT INTO extra_key (key_value,key_value_latin) select 'деньги в кредит',encodestring('деньги в кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'заявка на кредит',encodestring('заявка на кредит');
INSERT INTO extra_key (key_value,key_value_latin) select 'ипотека',encodestring('ипотека');