INSERT INTO `region` (`region_name`,`region_name_latin`) values
('Алтайский край',REPLACE(encodestring('Алтайский край')COLLATE utf8_unicode_ci ,' ','-')),
('Архангельская область',REPLACE(encodestring('Архангельская область')COLLATE utf8_unicode_ci ,' ','-')),
('Астраханская область',REPLACE(encodestring('Астраханская область')COLLATE utf8_unicode_ci ,' ','-')),
('Белгородская область',REPLACE(encodestring('Белгородская область')COLLATE utf8_unicode_ci ,' ','-')),
('Брянская область',REPLACE(encodestring('Брянская область')COLLATE utf8_unicode_ci ,' ','-')),
('Владимирская область',REPLACE(encodestring('Владимирская область')COLLATE utf8_unicode_ci ,' ','-')),
('Волгоградская область',REPLACE(encodestring('Волгоградская область')COLLATE utf8_unicode_ci ,' ','-')),
('Вологодская область',REPLACE(encodestring('Вологодская область')COLLATE utf8_unicode_ci ,' ','-')),
('Воронежская область',REPLACE(encodestring('Воронежская область')COLLATE utf8_unicode_ci ,' ','-')),
('Еврейская автономная область',REPLACE(encodestring('Еврейская автономная область')COLLATE utf8_unicode_ci ,' ','-')),
('Забайкальский край',REPLACE(encodestring('Забайкальский край')COLLATE utf8_unicode_ci ,' ','-')),
('Ивановская область',REPLACE(encodestring('Ивановская область')COLLATE utf8_unicode_ci ,' ','-')),
('Иркутская область',REPLACE(encodestring('Иркутская область')COLLATE utf8_unicode_ci ,' ','-')),
('Калининградская область',REPLACE(encodestring('Калининградская область')COLLATE utf8_unicode_ci ,' ','-')),
('Калужская область',REPLACE(encodestring('Калужская область')COLLATE utf8_unicode_ci ,' ','-')),
('Кемеровская область',REPLACE(encodestring('Кемеровская область')COLLATE utf8_unicode_ci ,' ','-')),
('Кировская область',REPLACE(encodestring('Кировская область')COLLATE utf8_unicode_ci ,' ','-')),
('Костромская область',REPLACE(encodestring('Костромская область')COLLATE utf8_unicode_ci ,' ','-')),
('Краснодарский край',REPLACE(encodestring('Краснодарский край')COLLATE utf8_unicode_ci ,' ','-')),
('Красноярский край',REPLACE(encodestring('Красноярский край')COLLATE utf8_unicode_ci ,' ','-')),
('Курганская область',REPLACE(encodestring('Курганская область')COLLATE utf8_unicode_ci ,' ','-')),
('Курская область',REPLACE(encodestring('Курская область')COLLATE utf8_unicode_ci ,' ','-')),
('Ленинградская область',REPLACE(encodestring('Ленинградская область')COLLATE utf8_unicode_ci ,' ','-')),
('Липецкая область',REPLACE(encodestring('Липецкая область')COLLATE utf8_unicode_ci ,' ','-')),
('Московская область',REPLACE(encodestring('Московская область')COLLATE utf8_unicode_ci ,' ','-')),
('Мурманская область',REPLACE(encodestring('Мурманская область')COLLATE utf8_unicode_ci ,' ','-')),
('Нижегородская область',REPLACE(encodestring('Нижегородская область')COLLATE utf8_unicode_ci ,' ','-')),
('Новгородская область',REPLACE(encodestring('Новгородская область')COLLATE utf8_unicode_ci ,' ','-')),
('Новосибирская область',REPLACE(encodestring('Новосибирская область')COLLATE utf8_unicode_ci ,' ','-')),
('Омская область',REPLACE(encodestring('Омская область')COLLATE utf8_unicode_ci ,' ','-')),
('Оренбургская область',REPLACE(encodestring('Оренбургская область')COLLATE utf8_unicode_ci ,' ','-')),
('Орловская область',REPLACE(encodestring('Орловская область')COLLATE utf8_unicode_ci ,' ','-')),
('Пензенская область',REPLACE(encodestring('Пензенская область')COLLATE utf8_unicode_ci ,' ','-')),
('Пермский край',REPLACE(encodestring('Пермский край')COLLATE utf8_unicode_ci ,' ','-')),
('Приморский край',REPLACE(encodestring('Приморский край')COLLATE utf8_unicode_ci ,' ','-')),
('Псковская область',REPLACE(encodestring('Псковская область')COLLATE utf8_unicode_ci ,' ','-')),
('Республика Адыгея',REPLACE(encodestring('Республика Адыгея')COLLATE utf8_unicode_ci ,' ','-')),
('Республика Алтай',REPLACE(encodestring('Республика Алтай')COLLATE utf8_unicode_ci ,' ','-')),
('Республика Башкортостан',REPLACE(encodestring('Республика Башкортостан')COLLATE utf8_unicode_ci ,' ','-')),
('Республика Бурятия',REPLACE(encodestring('Республика Бурятия')COLLATE utf8_unicode_ci ,' ','-')),
('Республика Дагестан',REPLACE(encodestring('Республика Дагестан')COLLATE utf8_unicode_ci ,' ','-')),
('Республика Кабардино-Балкария',REPLACE(encodestring('Республика Кабардино-Балкария')COLLATE utf8_unicode_ci ,' ','-')),
('Республика Калмыкия',REPLACE(encodestring('Республика Калмыкия')COLLATE utf8_unicode_ci ,' ','-')),
('Республика Карачаево-Черкесия',REPLACE(encodestring('Республика Карачаево-Черкесия')COLLATE utf8_unicode_ci ,' ','-')),
('Республика Карелия',REPLACE(encodestring('Республика Карелия')COLLATE utf8_unicode_ci ,' ','-')),
('Республика Коми',REPLACE(encodestring('Республика Коми')COLLATE utf8_unicode_ci ,' ','-')),
('Республика Марий Эл',REPLACE(encodestring('Республика Марий Эл')COLLATE utf8_unicode_ci ,' ','-')),
('Республика Мордовия',REPLACE(encodestring('Республика Мордовия')COLLATE utf8_unicode_ci ,' ','-')),
('Республика Саха - Якутия',REPLACE(encodestring('Республика Саха - Якутия')COLLATE utf8_unicode_ci ,' ','-')),
('Республика Северная Осетия-Алания',REPLACE(encodestring('Республика Северная Осетия-Алания')COLLATE utf8_unicode_ci ,' ','-')),
('Республика Татарстан',REPLACE(encodestring('Республика Татарстан')COLLATE utf8_unicode_ci ,' ','-')),
('Республика Тыва',REPLACE(encodestring('Республика Тыва')COLLATE utf8_unicode_ci ,' ','-')),
('Республика Удмуртия',REPLACE(encodestring('Республика Удмуртия')COLLATE utf8_unicode_ci ,' ','-')),
('Республика Хакасия',REPLACE(encodestring('Республика Хакасия')COLLATE utf8_unicode_ci ,' ','-')),
('Республика Чувашия',REPLACE(encodestring('Республика Чувашия')COLLATE utf8_unicode_ci ,' ','-')),
('Ростовская область',REPLACE(encodestring('Ростовская область')COLLATE utf8_unicode_ci ,' ','-')),
('Рязанская область',REPLACE(encodestring('Рязанская область')COLLATE utf8_unicode_ci ,' ','-')),
('Самарская область',REPLACE(encodestring('Самарская область')COLLATE utf8_unicode_ci ,' ','-')),
('Саратовская область',REPLACE(encodestring('Саратовская область')COLLATE utf8_unicode_ci ,' ','-')),
('Сахалинская область',REPLACE(encodestring('Сахалинская область')COLLATE utf8_unicode_ci ,' ','-')),
('Свердловская область',REPLACE(encodestring('Свердловская область')COLLATE utf8_unicode_ci ,' ','-')),
('Смоленская область',REPLACE(encodestring('Смоленская область')COLLATE utf8_unicode_ci ,' ','-')),
('Ставропольский край',REPLACE(encodestring('Ставропольский край')COLLATE utf8_unicode_ci ,' ','-')),
('Тамбовская область',REPLACE(encodestring('Тамбовская область')COLLATE utf8_unicode_ci ,' ','-')),
('Тверская область',REPLACE(encodestring('Тверская область')COLLATE utf8_unicode_ci ,' ','-')),
('Томская область',REPLACE(encodestring('Томская область')COLLATE utf8_unicode_ci ,' ','-')),
('Тульская область',REPLACE(encodestring('Тульская область')COLLATE utf8_unicode_ci ,' ','-')),
('Тюменская область',REPLACE(encodestring('Тюменская область')COLLATE utf8_unicode_ci ,' ','-')),
('Ульяновская область',REPLACE(encodestring('Ульяновская область')COLLATE utf8_unicode_ci ,' ','-')),
('Хабаровский край',REPLACE(encodestring('Хабаровский край')COLLATE utf8_unicode_ci ,' ','-')),
('Ханты-Мансийский автономный округ - Югра',REPLACE(encodestring('Ханты-Мансийский автономный округ - Югра')COLLATE utf8_unicode_ci ,' ','-')),
('Челябинская область',REPLACE(encodestring('Челябинская область')COLLATE utf8_unicode_ci ,' ','-')),
('Ямало-Ненецкий автономный округ',REPLACE(encodestring('Ямало-Ненецкий автономный округ')COLLATE utf8_unicode_ci ,' ','-')),
('Ярославская область',REPLACE(encodestring('Ярославская область')COLLATE utf8_unicode_ci ,' ','-'));